In [7]:
import torch
import tensorflow as tf

## For Torch

In [3]:
x = torch.tensor([1., 3., 8.])
y = torch.tensor([-4., 6., -2.])

In [4]:
# Calculating the DOT Product
x.dot(y)


tensor(-2.)

In [6]:
# Matrix multiplication of 2 D matrix
a = torch.tensor([[4, 4], [12, 16]])
b = torch.tensor([[7, 10], [12, 40]])
torch.matmul(a,b)


tensor([[ 76, 200],
        [276, 760]])

## For Tensorflow

In [8]:
x = tf.constant([1., 3., 8.])
y = tf.constant([-4., 6., -2.])

In [10]:
# Calculating the DOT Product

tf.reduce_sum(tf.multiply(x, y))


<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [11]:
# Matrix multiplication of 2 D matrix
a = tf.constant([[4, 4], [12, 16]])
b = tf.constant([[7, 10], [12, 40]])
a @ b


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 76, 200],
       [276, 760]])>